cookery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("dinner/", include("dinner.urls")),
    path('admin/', admin.site.urls),
]

dinner/urls.py
from django.urls import path
from . import views

app_name = "dinner"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:recipe_id>", views.recipe_detail, name="detail"),
    path("new", views.new_recipe, name="new_recipe"),
    path("create", views.create_recipe, name="create_recipe"),
    path("random", views.random_id, name="random_recipe"),
    path("ingredients", views.get_ingredients, name="ingredients"),
]

dinner/models.py
from django.db import models

class Recipe(models.Model):
    name = models.CharField(max_length=200)
    instructions = models.CharField(max_length=5000)

    class Meta:
        ordering = ['name']

class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    recipe = models.ManyToManyField(Recipe)

    class Meta:
        ordering = ['name']

dinner/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from .models import Recipe, Ingredient
from random import randint

def index(request):
    recipes = Recipe.objects.all()

    return render(request, "dinner/index.html", {"recipes": recipes})

def new_recipe(request):
    name = ""
    return render(request, "dinner/new_recipe.html")


def recipe_detail(request, recipe_id):
    recipe_info = get_object_or_404(Recipe, pk=recipe_id)

    return render(request, "dinner/recipe_detail.html", {"recipe": recipe_info})

def create_recipe(request):
    try:
        name = request.POST['recipe_name']
        instructions = request.POST['recipe_instructions']
    except(KeyError):
        return HttpResponseRedirect(reverse('dinner:index'))
    else:
        recipe = Recipe(name=name, instructions=instructions)
        recipe.save()
    return HttpResponseRedirect(reverse('dinner:index'))

def get_ingredients(request):
    resp = []
    try:
        ingredients = Ingredient.objects.all()
        for i in ingredients:
            resp.append(i.name)

    except (ObjectDoesNotExist):
        ingredients = []
    return JsonResponse({"ingredients": resp})

def random_id(request):
    recipes = Recipe.objects.all()
    random_recipe = randint(0, len(recipes) - 1)
    return HttpResponseRedirect(reverse('dinner:detail', args=[recipes[random_recipe].id]))

dinner/templates/dinner/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Cookery</title>
  </head>
  <body>
    <h1>Cookery</h1>

    <h2>Recipes</h2>
    <div>
      <ul>
        {% for recipe in recipes %}
        <li><a href="{% url 'dinner:detail' recipe.id %}">{{recipe.name}}</a></li>
        {% endfor %}
      </ul>
    </div>

    <a href="{% url 'dinner:random_recipe' %}">Random Recipe</a>
    <a href="{% url 'dinner:new_recipe' %}">New Recipe</a>
  </body>
</html>

dinner/templates/dinner/new_recipe.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Cookery: New Recipe</title>
  </head>
  <body>
    <h1>New Recipe</h1>
    <label for="recipe-name">Name</label>
    <input type="text" name="recipe_name" id="recipe-name">
    <div id="ingredient-inputs">
      <button id="add-ingredient">Add Ingredient</button>
      <select name="select-ingredient" id="select-ingredient">
      </select>
    </div>
    <h4>Ingredients</h4>
    <ul id="ingredient-list"></ul>
    <textarea name="recipe_instructions" id="recipe_instructions" form="create_form" cols="30" rows="10"></textarea>
    <button type="submit">Add Recipe</button>

    <script src="{% static 'dinner/new_recipe.js' %}"></script>
  </body>
</html>

dinner/templates/dinner/recipe_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Cookery: Detail</title>
  </head>
  <body>
    <h1>{{ recipe.name }}</h1>

    <a href="{% url 'dinner:index' %}">Home</a>

    <p>
      {{recipe.instructions}}
    </p>
  </body>
</html>